### ISSUE TITLE
图片请求错误？

### ISSUE THREAD

**Issue by TanyaBlanc** [xiaotianxt/PKU-Thesis-Download#3]
感谢脚本！之前的使用一直很流畅，但是最近尝试下载的时候pdf都是完全空白的……
页面左侧图标正常，pdf页数和网页中也是一样的，推测是请求图片这一步出现了问题……？

**Comment by Zebartin** [comment]
可以先选别的清晰度再选回“标清”试试。

盲猜是这里出了问题
https://github.com/xiaotianxt/PKU-Thesis-Download/blob/9b9d76b70d9686f3439ee057d4fac848744c7dcd/main.js#L153

或者初始化时把`localStorage`对应值设置成`2f`？

**Comment by xiaotianxt** [comment]
> 可以先选别的清晰度再选回“标清”试试。
> 
> 盲猜是这里出了问题
> 
> https://github.com/xiaotianxt/PKU-Thesis-Download/blob/9b9d76b70d9686f3439ee057d4fac848744c7dcd/main.js#L153
> 
> 或者初始化时把`localStorage`对应值设置成`2f`？

确实是这里的问题, 我现在就修😭

**Comment by xiaotianxt** [comment]
> 感谢脚本！之前的使用一直很流畅，但是最近尝试下载的时候pdf都是完全空白的……
> 
> 页面左侧图标正常，pdf页数和网页中也是一样的，推测是请求图片这一步出现了问题……？

已经修复好了，如果没有弹出更新，可以手动去[重新安装](https://greasyfork.org/zh-CN/scripts/442310-pku-thesis-download)一次。

**Comment by xiaotianxt** [comment]
> 感谢脚本！之前的使用一直很流畅，但是最近尝试下载的时候pdf都是完全空白的……
> 
> 页面左侧图标正常，pdf页数和网页中也是一样的，推测是请求图片这一步出现了问题……？

已经修复了，如果没有弹出更新，可以重新[手动安装](https://greasyfork.org/zh-CN/scripts/442310-pku-thesis-download)看看

**Comment by TanyaBlanc** [comment]
> > 感谢脚本！之前的使用一直很流畅，但是最近尝试下载的时候pdf都是完全空白的……
> > 页面左侧图标正常，pdf页数和网页中也是一样的，推测是请求图片这一步出现了问题……？
> 
> 已经修复了，如果没有弹出更新，可以重新[手动安装](https://greasyfork.org/zh-CN/scripts/442310-pku-thesis-download)看看

再次感谢！！
