### ISSUE TITLE
如何访问数据库查看学位论文

### ISSUE THREAD

**Issue by qqliang** [xiaotianxt/PKU-Thesis-Download#6]
作者您好！请问如何获取北大学位论文数据库的访问权限呢？

**Comment by xiaotianxt** [comment]
考入北大
2024年5月22日 +0800 PM9:51 liang qingqing ***@***.***>，写道：

**Comment by qqliang** [comment]
> 考入北大 2024年5月22日 +0800 PM9:51 liang qingqing ***@***.***>，写道：
> […](#)
> 作者您好！请问如何获取北大学位论文数据库的访问权限呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

泪目，打扰了
